### ISSUE TITLE
Tests don't work

### ISSUE THREAD

**Issue by fomkin** [JetBrains/tc-sbt-runner#7]
I have a some SBT projects with tests (Specs2, utest). Projects runs successful but I don't see any test reports in build log or "Tests" tab (however I don't see "Tests" tab at all). That it can be?

SBT Commands: test publish assembly
Teamcity Version: 9.0 (build 32060)
Plugin version: snapshot-20152001143429

**Comment by savulchik** [comment]
@yelbota see the https://github.com/JetBrains/tc-sbt-runner/issues/6#issuecomment-71258230 
> there is a problem with latest versions of SBT (>=0.13.6) - the runner doesn't help to much

I confirm that tc-sbt-runner successfully reports test results for projects using sbt 0.13.5. But fails for sbt 0.13.7.

**Comment by fractal** [comment]
do you use the auto configured plugin or a custom SBT installation? I can only get correct reportings from the custom execution. The autoinstalled reports my tests twice, and doesn't use the .sbt home folder
